In [1]:
import numpy as np
import pandas as pd

## read a file and print its lines

In [6]:
#create a file in the name of 'python' in notepad.write some lines and save the file in the same folder 
#where you are saving this notepad.
myfile = open('python.txt', 'r')
count = 0
 
# Using while loop
print("Using while loop\n") 
while True:
    count += 1
 
    # Get next line from file
    line = myfile.readline()
 
    # if line is empty
    # end of file is reached
    if not line:
        break
    print("Line{}: {}".format(count, line.strip()))
myfile.close()

Using while loop

Line1: Python is an interpreted high-level general-purpose
Line2: programming language. Its design philosophy emphasizes
Line3: code readability with its use of significant indentation.
Line4: Its language constructs as well as its object-oriented
Line5: approach aim to help programmers write clear, logical
Line6: code for small and large-scale
Line7: projects.


In [7]:
myfile = open('python.txt', 'r')
count = 0
 
# Using for loop
print("Using for loop\n")

for line in myfile :
    count += 1
    print("Line{}: {}".format(count, line.strip()))
#Closing files
myfile.close()

Using for loop

Line1: Python is an interpreted high-level general-purpose
Line2: programming language. Its design philosophy emphasizes
Line3: code readability with its use of significant indentation.
Line4: Its language constructs as well as its object-oriented
Line5: approach aim to help programmers write clear, logical
Line6: code for small and large-scale
Line7: projects.


In [9]:
# Using readline
print("Using readline\n")

with open("python.txt") as fp:
    while True:
        count += 1
        line = fp.readline()
 
        if not line:
            break
        print("Line{}: {}".format(count, line.strip()))

Using readline

Line15: Python is an interpreted high-level general-purpose
Line16: programming language. Its design philosophy emphasizes
Line17: code readability with its use of significant indentation.
Line18: Its language constructs as well as its object-oriented
Line19: approach aim to help programmers write clear, logical
Line20: code for small and large-scale
Line21: projects.


## reverse an array without using the in built functions

In [14]:
def reverse_list(arr): 
    return arr[::-1]

before_reverse = [1,2,3,4,5,6,7,8,9,10]
print('The Original array is :\t',before_reverse)

reversed_arr = reverse_list(before_reverse )
print('\nThe Reversed array is :\t',reversed_arr)

The Original array is :	 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The Reversed array is :	 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [20]:
def reverse_list1(arr):
    end = len(arr)-1
    limit = int(end/2) + 1
    for i in range(limit):
        arr[i],arr[end] = arr[end],arr[i]
        end = end - 1
    return arr

before_reverse = [1,2,3,4,5,6,7,8,9,10]
print('The Original array is :\t',before_reverse)

reversed_arr = reverse_list1(before_reverse )
print('\nThe Reversed array is :\t',reversed_arr)

The Original array is :	 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The Reversed array is :	 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [21]:
def reverse_list2(arr):
    left = 0
    right = len(arr) - 1
    while left < right:
        arr[left], arr[right] = arr[right], arr[left]
        left += 1
        right -= 1
    return arr

before_reverse = [1,2,3,4,5,6,7,8,9,10]
print('The Original array is :\t',before_reverse)

reversed_arr = reverse_list2(before_reverse )
print('\nThe Reversed array is :\t',reversed_arr)

The Original array is :	 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The Reversed array is :	 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [22]:
def reverse_list3(arr):
    return [arr[-i] for i in range(1, len(arr) + 1)]

before_reverse = [1,2,3,4,5,6,7,8,9,10]
print('The Original array is :\t',before_reverse)

reversed_arr = reverse_list3(before_reverse )
print('\nThe Reversed array is :\t',reversed_arr)

The Original array is :	 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The Reversed array is :	 [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## using loops to iterate through nested dictionary/list python

In [24]:
details = {
            'ID 1':    {'Name': 'Shaun', 'Age': 35, 'City': 'Delhi'},
            'ID 2':    {'Name': 'Ritika', 'Age': 31, 'City': 'Mumbai'},
            'ID 3':    {'Name': 'Smriti', 'Age': 33, 'City': 'Sydney'},
            'ID 4':    {'Name': 'Jacob', 'Age': 23, 'City': {'perm': 'Tokyo',
                                                             'current': 'London'}}
}

In [28]:
def nested_loop_dict(obj):
    # Iterate over all key-value pairs of dict argument
    for key, value in obj.items():
        # Check if value is of dict type
        if isinstance(value, dict):
            # If value is dict then iterate over all its values
            for pair in  nested_loop_dict(value):
                yield (key, *pair)
        else:
            # If value is not dict type then yield the value
            yield (key, value)
#Loop through all key-value pairs of a nested dictionary
print('Iterating over Nested Dict:')
for pair in nested_loop_dict(details):
    print('\n',pair)

Iterating over Nested Dict:

 ('ID 1', 'Name', 'Shaun')

 ('ID 1', 'Age', 35)

 ('ID 1', 'City', 'Delhi')

 ('ID 2', 'Name', 'Ritika')

 ('ID 2', 'Age', 31)

 ('ID 2', 'City', 'Mumbai')

 ('ID 3', 'Name', 'Smriti')

 ('ID 3', 'Age', 33)

 ('ID 3', 'City', 'Sydney')

 ('ID 4', 'Name', 'Jacob')

 ('ID 4', 'Age', 23)

 ('ID 4', 'City', 'perm', 'Tokyo')

 ('ID 4', 'City', 'current', 'London')


In [32]:
people = {1: {'Name': 'John', 'Age': '27', 'Sex': 'Male'},
        2: {'Name': 'Marie', 'Age': '22', 'Sex': 'Female'}}

for p_id, info in people.items():
    print("\nID:", p_id)
    for key in info:
        print(key + ':', info[key])


ID: 1
Name: John
Age: 27
Sex: Male

ID: 2
Name: Marie
Age: 22
Sex: Female


In [33]:
rhymes = [['cat', 'hat', 'fat'], ['mouse', 'house', 'louse'], ['be', 'see', 'key', 'he']]

In [36]:
def nested_loop_list(obj):
    for value in obj:
        # Check if value is of list type
            if isinstance(value, list):
            # If value is list then iterate over all its values
                nested_loop_list(value)
            else:
            # If value is not list type then print the value
                print('\n',value)
                
#Loop through all values of a nested list
print('Iterating over Nested List:')
nested_loop_list(rhymes)

Iterating over Nested List:

 cat

 hat

 fat

 mouse

 house

 louse

 be

 see

 key

 he


## concatenate 2 arrays

In [37]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

print('concatenating 2 arrays : \n',np.concatenate((a, b), axis=0))

concatenating 2 arrays : 
 [[1 2]
 [3 4]
 [5 6]]


In [38]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6],[7,8]])

print('concatenating 2 arrays : \n',np.concatenate((a, b), axis=1))

concatenating 2 arrays : 
 [[1 2 5 6]
 [3 4 7 8]]


In [39]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print('concatenating 2 arrays : \n',arr)

concatenating 2 arrays : 
 [[1 4]
 [2 5]
 [3 6]]


In [47]:
list1 = [1, 4, 5, 6, 5]
list2 = [3, 5, 7, 2, 5]

for i in list2 :
    list1.append(i)

print ("Concatenated list : " ,list1)

Concatenated list :  [1, 4, 5, 6, 5, 3, 5, 7, 2, 5]


In [45]:
list3 = [1, 4, 5, 6, 5]
list4 = [3, 5, 7, 2, 5]
  
# using + operator to concat
list3 = list3 + list4
  
# Printing concatenated list
print ("Concatenated list : " ,list3)

Concatenated list :  [1, 4, 5, 6, 5, 3, 5, 7, 2, 5]


## sum of digits of a number

In [50]:
def sum_Of_Digits(num):
    #Initialize sum with 0
    sum =0
    while num>0:
        sum += num%10
        num = num//10
    return sum
    
num = int(input("Enter a Number: "))
print("Sum of the digits: ",sum_Of_Digits(num))

Enter a Number: 2158
Sum of the digits:  16


In [51]:
n=input("Enter a Number :")
sum=0
for i in range(0,len(n)):
    sum=sum+int(n[i])
    
print("sum of digits in number : ", sum)

Enter a Number :5483
sum of digits in number :  20


In [53]:
def sum_dig(n):
    
    sum = 0
    for num in str(n): 
        sum += int(num)      
    return sum

#getting number as input  
n = int(input("Enter a number: "))
print("sum of digits in number : ",sum_dig(n))

Enter a number: 2158
sum of digits in number :  16


In [55]:
def sum_dig(n):
    
    sum = 0
    for num in n: 
        sum += int(num)      
    return sum

#getting string as input   
n = input("Enter a number: ")
print("sum of digits in number : ",sum_dig(n))

Enter a number: 2158
sum of digits in number :  16
